scheduled_tweets/config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  get "/about", to: "about#index"

  get "password", to:"passwords#edit", as: 'edit_password'
  patch "password", to:"passwords#update", as: 'password'

  get "/sign_up", to: "registrations#signup"
  post "sign_up", to: "registrations#create"
 
  get "/sign_in", to: "sessions#signin"
  post "sign_in", to: "sessions#create" 

  delete "/logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#forgotpassword"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
 # root to: "main#index"

end

scheduled_tweets/app/models/concerns/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
  end
  

scheduled_tweets/app/models/user.rb
#email:string
#password_digest:string
#
#password:string virtual
#password_configuration:string virtual
class User < ApplicationRecord
   has_secure_password
   validates :password, presence: true, confirmation: true, format: { with: /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}\z/, message: "Password should match the specified format" }
   validates :email, presence: true, format: {with: /\A[^@\s]+@[^@\s]+\z/, message: " Must be a valid email address! " }
end

scheduled_tweets/app/controllers/about_controller.rb
class AboutController < ApplicationController
def index
end
end

scheduled_tweets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user 
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
    end
end

scheduled_tweets/app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

scheduled_tweets/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
      # Your logic for rendering the password reset form goes here
    end
  
    def create
      @user = User.find_by(email: params[:email])
  
      if @user.present?
        # Send password reset email
        PasswordResetMailer.with(user: @user).reset.deliver_now
      end
  
      redirect_to root_path, notice: "If an account with this email was found, we have sent a link to reset your password."
    end
  
    def edit
      @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to sign_in_path, alert: "Your token has expired. Please try again."
    end
  
    def update
      @user = User.find_signed!(params[:token], purpose: "password_reset")
      if @user.update(password_params)
        redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
      else
        render :edit
      end
    end
  
    private
  
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end
  

scheduled_tweets/app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    def  edit
    end

    def update 
        if Current.user.update(password_params)
            redirect_to root_path, notice: "password updated!"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

scheduled_tweets/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def signup
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
      render:signup
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

scheduled_tweets/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def signin
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id 
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash.now[:alert] = "Invalid email or password"
            render:signin
        end
    end

    def destroy 
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

scheduled_tweets/app/helpers/main_helper.rb
module MainHelper
end

scheduled_tweets/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

scheduled_tweets/app/helpers/passwords_helper.rb
module PasswordsHelper
end

scheduled_tweets/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

scheduled_tweets/app/views/about/index.html.erb
<h1> About Us </h1>.object.errors.any? %>
            <div class="alert alert-danger">
                <%= form.object.errors.full_messages.each do |message| %>
                   
                <% end %>
            </div>
    <% end %>
    
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: " form-control ", placeholder: "password"  %>
    </div>

scheduled_tweets/app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>ISADU</h1>
</div>
<% if Current.user%>
    <li class="nav-item">
        <span><%= Current.user.email %></span>

    </li>
    <li class="nav-item">
        <%= button_to "Logout", logout_path, method: :delete, class: "nav-link"  %>
     </li>

<% end %> 

scheduled_tweets/app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
     <% if form.object.errors.any? %>
            <div class="alert alert-danger">
                <%= form.object.errors.full_messages.each do |message| %>
                   
                <% end %>
            </div>
    <% end %>
    
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: " form-control ", placeholder: "password"  %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset password", class: "btn btn-primary" %>
    </div>
<% end %>  

scheduled_tweets/app/views/password_resets/forgotpassword.html.erb
<h1>Forgot your password</h1>

<%= form_with(url: password_reset_path, method: :post) do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: " form-control ", placeholder: "email@gmail.com"  %>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset password", class: "btn btn-primary" %>
    </div>
<% end %>  

scheduled_tweets/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #63cdda;">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link text-white" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-sm btn-outline-light" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link text-white"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", sign_in_path, class: "nav-link text-white"  %>
        </li>
      </ul>
    </div>
  </div>
</nav>