visa_application/config/routes.rb
Rails.application.routes.draw do
  resources :documents, only: [:new, :create, :index, :show]
  get 'dashboard', to: 'dashboard#index'
  root to: 'documents#index'
end

visa_application/app/models/document.rb
class Document < ApplicationRecord
    mount_uploader :file_data, DocumentUploader
  
    # Add the 'name' attribute to the whitelist of attributes
    attr_accessor :name
  end
  

visa_application/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
      # Your dashboard logic goes here
    end
  end
  

visa_application/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    def index
      @documents = Document.all
    end
  
    def new
      @document = Document.new
    end
  
    def create
      @document = Document.new(document_params)
  
      if @document.save
        redirect_to documents_path, notice: 'Document uploaded successfully.'
      else
        render :new
      end
    end
  
    def show
      @document = Document.find(params[:id])
    end
  
    private
  
    def document_params
      params.require(:document).permit(:name, :file_data)
    end
  end
  

visa_application/app/helpers/dashboard_helper.rb
module DashboardHelper
end

visa_application/app/helpers/documents_helper.rb
module DocumentsHelper
end

visa_application/app/views/dashboard/index.html.erb
<!-- app/views/dashboard/index.html.erb -->

<h1>Dashboard</h1>

<p>Your dashboard content goes here.</p>

visa_application/app/views/documents/index.html.erb
<!-- app/views/documents/index.html.erb -->

<h1>Your Uploaded Documents</h1>

<% @documents.each do |document| %>
  <div class="document">
    <%= link_to document.name, document_path(document) %>
  </div>
<% end %>

visa_application/app/views/documents/new.html.erb
<%= form_with(model: @document, local: true) do |f| %>
  <div class="mb-3">
    <%= f.label :file_data, class: "form-label" %>
    <%= f.file_field :file_data, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.submit "Upload Document", class: "btn btn-primary" %>
  </div>
<% end %>

visa_application/app/views/documents/show.html.erb
<!-- app/views/documents/show.html.erb -->

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>File:</strong>
  <%= link_to 'Download File', @document.file_data_url %> <!-- Assuming you have a method like file_data_url in your Document model -->
</p>

visa_application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Rails App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom_styles', media: 'all' %>
    <%= stylesheet_link_tag 'bootstrap', media: 'all' %> <!-- Add this line -->

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'bootstrap' %> <!-- Add this line -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>